// src/config/env.ts
import dotenv from "dotenv";
import path from "path";
import { z } from "zod";

dotenv.config({ path: path.resolve(__dirname, "../../.env") });

const envSchema = z.object({
  RAZORPAY_KEY_ID: z.string(),
  RAZORPAY_KEY_SECRET: z.string(),
  RAZORPAY_WEBHOOK_SECRET: z.string(),
  PORT: z.string().default("3000"),
  FRONTEND_URL: z.string().default("http://localhost:3000"),
  CORS_ORIGINS: z.string().optional(),
  NODE_ENV: z
    .enum(["development", "production", "test"])
    .default("development"),
  DB_HOST: z.string(),
  DB_PORT: z.string().default("5432"),
  DB_USERNAME: z.string(),
  DB_PASSWORD: z.string(),
  DB_NAME: z.string(),
  DB_SSL: z
    .string()
    .default("true")
    .transform((value) => value === "true"),
  REDIS_HOST: z.string().default("localhost"),
  REDIS_PORT: z.string().default("6379"),
  REDIS_PASSWORD: z.string().optional(),
  JWT_SECRET: z.string(),
  JWT_EXPIRES_IN: z.string().default("7d"),
  OPENAI_API_KEY: z.string(),
  OPENAI_IMAGE_MODEL: z.string().default("gpt-image-1"),
  AWS_ACCESS_KEY_ID: z.string(),
  AWS_SECRET_ACCESS_KEY: z.string(),
  AWS_REGION: z.string().default("us-east-1"),
  AWS_BUCKET_NAME: z.string(),
  STORAGE_DRIVER: z.enum(["s3", "local"]).default("s3"),
  BACKEND_PUBLIC_URL: z.string().default("http://localhost:3001"),
  IMAGE_GENERATION_API_URL: z.string().default("http://localhost:8000"),
  VIDEO_WORKER_API_URL: z.string().default("http://localhost:8001"),
  VIDEO_API_KEY: z.string().optional(),
  VIDEO_AUTH_SCHEME: z.string().default(""),
  VIDEO_IMAGE_FIELD: z.string().default("image"),
  VIDEO_PROMPT_FIELD: z.string().default("prompt"),
  VIDEO_DURATION_FIELD: z.string().default("duration"),
  VIDEO_DURATION: z.string().default("5"),
  VIDEO_OUTPUT_FIELD: z.string().default("video_url"),
  VIDEO_TASK_ID_FIELD: z.string().default("output.task_id"),
  VIDEO_TASK_STATUS_FIELD: z.string().default("output.task_status"),
  VIDEO_MODEL: z.string().default("happyhorse-1.0-i2v"),
  VIDEO_RESOLUTION: z.string().default("1080P"),
  VIDEO_RATIO: z.string().default("16:9"),
  TRAINING_API_URL: z.string().default("http://localhost:8002"),
  RUNPOD_API_KEY: z.string().optional(),
  RUNPOD_AUTH_SCHEME: z.string().default(""),
  RUNPOD_ENDPOINT_ID: z.string().optional(),
  RUNPOD_BASE_URL: z.string().default("https://api.runpod.ai/v2"),
  RUNPOD_IMAGE_ENDPOINT_ID: z.string().optional(),
  RUNPOD_IMAGE_INPUT_TEMPLATE_PATH: z.string().optional(),
  RUNPOD_IMAGE_SKETCH_FIELD: z.string().default("sketch_image"),
  RUNPOD_IMAGE_PROMPT_FIELD: z.string().default("prompt"),
  RUNPOD_IMAGE_TRIGGER_FIELD: z.string().default("trigger_word"),
  RUNPOD_IMAGE_LORA_NAME_FIELD: z.string().default("lora_name"),
  RUNPOD_IMAGE_LORA_URL_FIELD: z.string().default("lora_url"),
  RUNPOD_IMAGE_WIDTH: z.string().default("1280"),
  RUNPOD_IMAGE_HEIGHT: z.string().default("720"),
  RUNPOD_IMAGE_OUTPUT_FIELD: z.string().default("images.0.data"),
  RUNPOD_IMAGE_BASE64_PREFIX: z
    .string()
    .default("false")
    .transform((value) => value === "true"),
  RUNPOD_VIDEO_IMAGE_FIELD: z.string().default("image_url"),
  RUNPOD_VIDEO_PROMPT_FIELD: z.string().default("prompt"),
  RUNPOD_VIDEO_DURATION: z.string().default("5"),
  RUNPOD_VIDEO_ASPECT_RATIO: z.string().default("16:9"),
  RUNPOD_VIDEO_OUTPUT_FIELD: z.string().default("video_url"),
  RUNPOD_POLL_INTERVAL_MS: z.string().default("5000"),
  RUNPOD_MAX_POLL_ATTEMPTS: z.string().default("120"),
  RUNPOD_EXECUTION_TIMEOUT_MS: z.string().default("900000"),
  RUNPOD_TTL_MS: z.string().default("1800000"),
});

const env = envSchema.parse(process.env);

export const config = {
  razorpay: {
    keyId: env.RAZORPAY_KEY_ID,
    keySecret: env.RAZORPAY_KEY_SECRET,
    webhookSecret: env.RAZORPAY_WEBHOOK_SECRET,
  },
  port: parseInt(env.PORT, 10),
  frontendUrl: env.FRONTEND_URL,
  corsOrigins: (env.CORS_ORIGINS || env.FRONTEND_URL)
    .split(",")
    .map((origin) => origin.trim())
    .filter(Boolean),
  nodeEnv: env.NODE_ENV,
  database: {
    host: env.DB_HOST,
    port: parseInt(env.DB_PORT, 10),
    username: env.DB_USERNAME,
    password: env.DB_PASSWORD,
    database: env.DB_NAME,
    ssl: env.DB_SSL ? { rejectUnauthorized: false } : false,
  },
  aws: {
    accessKeyId: env.AWS_ACCESS_KEY_ID,
    secretAccessKey: env.AWS_SECRET_ACCESS_KEY,
    region: env.AWS_REGION,
    bucketName: env.AWS_BUCKET_NAME,
  },
  storage: {
    driver: env.STORAGE_DRIVER,
    backendPublicUrl: env.BACKEND_PUBLIC_URL.replace(/\/$/, ""),
  },
  redis: {
    host: env.REDIS_HOST,
    port: parseInt(env.REDIS_PORT, 10),
    password: env.REDIS_PASSWORD,
  },
  jwt: {
    secret: env.JWT_SECRET,
    expiresIn: env.JWT_EXPIRES_IN,
  },
  openai: {
    apiKey: env.OPENAI_API_KEY,
    imageModel: env.OPENAI_IMAGE_MODEL,
  },
  workers: {
    imageGenerationApiUrl: env.IMAGE_GENERATION_API_URL,
    videoWorkerApiUrl: env.VIDEO_WORKER_API_URL,
    videoApiKey: env.VIDEO_API_KEY,
    videoAuthScheme: env.VIDEO_AUTH_SCHEME,
    videoImageField: env.VIDEO_IMAGE_FIELD,
    videoPromptField: env.VIDEO_PROMPT_FIELD,
    videoDurationField: env.VIDEO_DURATION_FIELD,
    videoDuration: env.VIDEO_DURATION,
    videoOutputField: env.VIDEO_OUTPUT_FIELD,
    videoTaskIdField: env.VIDEO_TASK_ID_FIELD,
    videoTaskStatusField: env.VIDEO_TASK_STATUS_FIELD,
    videoModel: env.VIDEO_MODEL,
    videoResolution: env.VIDEO_RESOLUTION,
    videoRatio: env.VIDEO_RATIO,
    trainingApiUrl: env.TRAINING_API_URL.replace(/\/$/, ""),
    runpodApiKey: env.RUNPOD_API_KEY,
    runpodAuthScheme: env.RUNPOD_AUTH_SCHEME,
    runpodEndpointId: env.RUNPOD_ENDPOINT_ID,
    runpodBaseUrl: env.RUNPOD_BASE_URL.replace(/\/$/, ""),
    runpodImageEndpointId: env.RUNPOD_IMAGE_ENDPOINT_ID || env.RUNPOD_ENDPOINT_ID,
    runpodImageInputTemplatePath: env.RUNPOD_IMAGE_INPUT_TEMPLATE_PATH,
    runpodImageSketchField: env.RUNPOD_IMAGE_SKETCH_FIELD,
    runpodImagePromptField: env.RUNPOD_IMAGE_PROMPT_FIELD,
    runpodImageTriggerField: env.RUNPOD_IMAGE_TRIGGER_FIELD,
    runpodImageLoraNameField: env.RUNPOD_IMAGE_LORA_NAME_FIELD,
    runpodImageLoraUrlField: env.RUNPOD_IMAGE_LORA_URL_FIELD,
    runpodImageWidth: parseInt(env.RUNPOD_IMAGE_WIDTH, 10),
    runpodImageHeight: parseInt(env.RUNPOD_IMAGE_HEIGHT, 10),
    runpodImageOutputField: env.RUNPOD_IMAGE_OUTPUT_FIELD,
    runpodImageBase64Prefix: env.RUNPOD_IMAGE_BASE64_PREFIX,
    runpodVideoImageField: env.RUNPOD_VIDEO_IMAGE_FIELD,
    runpodVideoPromptField: env.RUNPOD_VIDEO_PROMPT_FIELD,
    runpodVideoDuration: env.RUNPOD_VIDEO_DURATION,
    runpodVideoAspectRatio: env.RUNPOD_VIDEO_ASPECT_RATIO,
    runpodVideoOutputField: env.RUNPOD_VIDEO_OUTPUT_FIELD,
    runpodPollIntervalMs: parseInt(env.RUNPOD_POLL_INTERVAL_MS, 10),
    runpodMaxPollAttempts: parseInt(env.RUNPOD_MAX_POLL_ATTEMPTS, 10),
    runpodExecutionTimeoutMs: parseInt(env.RUNPOD_EXECUTION_TIMEOUT_MS, 10),
    runpodTtlMs: parseInt(env.RUNPOD_TTL_MS, 10),
  },
};
